add_definitions(-D_CRT_SECURE_NO_WARNINGS)
set(BOOST_ROOT "c:/Build/boost_1_48_0")
set(Boost_USE_STATIC_LIBS TRUE)
set(Boost_ADDITIONAL_VERSIONS "1.48" "1.48.0")
set(Berkeley_ROOT "c:/Build/db-5.2.36")
set(Event2_INCLUDE_PATH "c:/Build/libevent-2.0.16-stable/include")
set(Event2_LIBRARY_DIR "c:/Build/libevent-2.0.16-stable/")
